# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FTSensorUserCfg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import pyrdk.protos.pb2.CommonDefs_pb2 as CommonDefs__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="FTSensorUserCfg.proto",
    package="proto",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x15\x46TSensorUserCfg.proto\x12\x05proto\x1a\x10\x43ommonDefs.proto"a\n\x14\x46TSensorPropertyData\x12\x14\n\x0cserialNumber\x18\x01 \x01(\t\x12\x0c\n\x04mass\x18\x02 \x01(\x02\x12\x14\n\x0c\x63\x65nterOfMass\x18\x03 \x03(\x02\x12\x0f\n\x07inertia\x18\x04 \x03(\x02"\x9a\x01\n\x13\x46TSensorUserCfgData\x12\x16\n\x0e\x65nableFTSensor\x18\x01 \x01(\x08\x12\x16\n\x0e\x65nableTempComp\x18\x02 \x01(\x08\x12 \n\x18\x66tSensorSlaveCfgFileName\x18\x03 \x01(\t\x12\x31\n\x0cpropertyData\x18\x04 \x01(\x0b\x32\x1b.proto.FTSensorPropertyDatab\x06proto3',
    dependencies=[
        CommonDefs__pb2.DESCRIPTOR,
    ],
)

_FTSENSORPROPERTYDATA = _descriptor.Descriptor(
    name="FTSensorPropertyData",
    full_name="proto.FTSensorPropertyData",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="serialNumber",
            full_name="proto.FTSensorPropertyData.serialNumber",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="mass",
            full_name="proto.FTSensorPropertyData.mass",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="centerOfMass",
            full_name="proto.FTSensorPropertyData.centerOfMass",
            index=2,
            number=3,
            type=2,
            cpp_type=6,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="inertia",
            full_name="proto.FTSensorPropertyData.inertia",
            index=3,
            number=4,
            type=2,
            cpp_type=6,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=50,
    serialized_end=147,
)

_FTSENSORUSERCFGDATA = _descriptor.Descriptor(
    name="FTSensorUserCfgData",
    full_name="proto.FTSensorUserCfgData",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="enableFTSensor",
            full_name="proto.FTSensorUserCfgData.enableFTSensor",
            index=0,
            number=1,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="enableTempComp",
            full_name="proto.FTSensorUserCfgData.enableTempComp",
            index=1,
            number=2,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="ftSensorSlaveCfgFileName",
            full_name="proto.FTSensorUserCfgData.ftSensorSlaveCfgFileName",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="propertyData",
            full_name="proto.FTSensorUserCfgData.propertyData",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=150,
    serialized_end=304,
)

_FTSENSORUSERCFGDATA.fields_by_name["propertyData"].message_type = _FTSENSORPROPERTYDATA
DESCRIPTOR.message_types_by_name["FTSensorPropertyData"] = _FTSENSORPROPERTYDATA
DESCRIPTOR.message_types_by_name["FTSensorUserCfgData"] = _FTSENSORUSERCFGDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FTSensorPropertyData = _reflection.GeneratedProtocolMessageType(
    "FTSensorPropertyData",
    (_message.Message,),
    {
        "DESCRIPTOR": _FTSENSORPROPERTYDATA,
        "__module__": "FTSensorUserCfg_pb2",
        # @@protoc_insertion_point(class_scope:proto.FTSensorPropertyData)
    },
)
_sym_db.RegisterMessage(FTSensorPropertyData)

FTSensorUserCfgData = _reflection.GeneratedProtocolMessageType(
    "FTSensorUserCfgData",
    (_message.Message,),
    {
        "DESCRIPTOR": _FTSENSORUSERCFGDATA,
        "__module__": "FTSensorUserCfg_pb2",
        # @@protoc_insertion_point(class_scope:proto.FTSensorUserCfgData)
    },
)
_sym_db.RegisterMessage(FTSensorUserCfgData)

# @@protoc_insertion_point(module_scope)
