# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IOPortSimDataDef.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name="IOPortSimDataDef.proto",
    package="proto",
    syntax="proto2",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x16IOPortSimDataDef.proto\x12\x05proto"r\n\nIOPortData\x12$\n\tdata_type\x18\x01 \x02(\x0e\x32\x11.proto.IOPortType\x12\x11\n\tport_name\x18\x02 \x02(\t\x12\x12\n\nport_value\x18\x03 \x02(\t\x12\x17\n\x08sim_flag\x18\x04 \x01(\x08:\x05\x66\x61lse*+\n\nIOPortType\x12\x08\n\x04\x42OOL\x10\x00\x12\x07\n\x03INT\x10\x01\x12\n\n\x06\x44OUBLE\x10\x02',
)

_IOPORTTYPE = _descriptor.EnumDescriptor(
    name="IOPortType",
    full_name="proto.IOPortType",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="BOOL",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="INT",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="DOUBLE",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=149,
    serialized_end=192,
)
_sym_db.RegisterEnumDescriptor(_IOPORTTYPE)

IOPortType = enum_type_wrapper.EnumTypeWrapper(_IOPORTTYPE)
BOOL = 0
INT = 1
DOUBLE = 2

_IOPORTDATA = _descriptor.Descriptor(
    name="IOPortData",
    full_name="proto.IOPortData",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="data_type",
            full_name="proto.IOPortData.data_type",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=2,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="port_name",
            full_name="proto.IOPortData.port_name",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="port_value",
            full_name="proto.IOPortData.port_value",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="sim_flag",
            full_name="proto.IOPortData.sim_flag",
            index=3,
            number=4,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=True,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=33,
    serialized_end=147,
)

_IOPORTDATA.fields_by_name["data_type"].enum_type = _IOPORTTYPE
DESCRIPTOR.message_types_by_name["IOPortData"] = _IOPORTDATA
DESCRIPTOR.enum_types_by_name["IOPortType"] = _IOPORTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IOPortData = _reflection.GeneratedProtocolMessageType(
    "IOPortData",
    (_message.Message,),
    {
        "DESCRIPTOR": _IOPORTDATA,
        "__module__": "IOPortSimDataDef_pb2",
        # @@protoc_insertion_point(class_scope:proto.IOPortData)
    },
)
_sym_db.RegisterMessage(IOPortData)

# @@protoc_insertion_point(module_scope)
