import os


ROBOT_NANOMSG_PORT = os.environ.get("ROBOT_NANOMSG_PORT", 15001)
ROBOT_NANOMSG_BLOCK_ON_DAIL = os.environ.get("ROBOT_NANOMSG_BLOCK_ON_DAIL", False)
ROBOT_NANOMSG_RECV_TIMEOUT = os.environ.get(
    "ROBOT_NANOMSG_RECV_TIMEOUT", 1000
)  # unit: ms
ROBOT_NANOMSG_RECONNECT_TIME_MIN = os.environ.get(
    "ROBOT_NANOMSG_RECONNECT_TIME_MIN", 1000
)  # unit: ms
ROBOT_NANOMSG_RECONNECT_TIME_MAX = os.environ.get(
    "ROBOT_NANOMSG_RECONNECT_TIME_MAX", 3000
)  # unit: ms

ROBOT_GRPC_PORT = os.environ.get("ROBOT_GRPC_PORT", 18001)
ROBOT_GRPC_RETRIES = os.environ.get("ROBOT_GRPC_RETRIES", 1)
ROBOT_GRPC_MIN_RECONNECT_BACKOFF = os.environ.get(
    "ROBOT_GRPC_MIN_RECONNECT_BACKOFF", 100
)  # unit: ms

MAPPING_RCA = "v3.11"