# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

import pyrdk.protos.pb2.CommonDefs_pb2 as CommonDefs__pb2
import pyrdk.protos.pb2.RemoteFileSystem_pb2 as RemoteFileSystem__pb2


class RemoteFileSystemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getRuntimeInfo = channel.unary_unary(
            "/proto.RemoteFileSystemService/getRuntimeInfo",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RemoteFileSystem__pb2.RuntimeInfoResponse.FromString,
        )
        self.list = channel.unary_unary(
            "/proto.RemoteFileSystemService/list",
            request_serializer=RemoteFileSystem__pb2.FileRequest.SerializeToString,
            response_deserializer=RemoteFileSystem__pb2.FileResponse.FromString,
        )
        self.recursiveList = channel.unary_unary(
            "/proto.RemoteFileSystemService/recursiveList",
            request_serializer=RemoteFileSystem__pb2.FileRequest.SerializeToString,
            response_deserializer=RemoteFileSystem__pb2.FileResponse.FromString,
        )
        self.read = channel.unary_unary(
            "/proto.RemoteFileSystemService/read",
            request_serializer=RemoteFileSystem__pb2.FileRequest.SerializeToString,
            response_deserializer=RemoteFileSystem__pb2.FileResponse.FromString,
        )
        self.write = channel.unary_unary(
            "/proto.RemoteFileSystemService/write",
            request_serializer=RemoteFileSystem__pb2.FileInfo.SerializeToString,
            response_deserializer=RemoteFileSystem__pb2.FileResponse.FromString,
        )
        self.writeStream = channel.stream_unary(
            "/proto.RemoteFileSystemService/writeStream",
            request_serializer=RemoteFileSystem__pb2.FileStreamInfo.SerializeToString,
            response_deserializer=RemoteFileSystem__pb2.FileStreamResponse.FromString,
        )
        self.readStream = channel.unary_stream(
            "/proto.RemoteFileSystemService/readStream",
            request_serializer=RemoteFileSystem__pb2.FileRequest.SerializeToString,
            response_deserializer=RemoteFileSystem__pb2.FileStreamResponse.FromString,
        )
        self.rename = channel.unary_unary(
            "/proto.RemoteFileSystemService/rename",
            request_serializer=RemoteFileSystem__pb2.FileRequest.SerializeToString,
            response_deserializer=RemoteFileSystem__pb2.FileResponse.FromString,
        )
        self.remove = channel.unary_unary(
            "/proto.RemoteFileSystemService/remove",
            request_serializer=RemoteFileSystem__pb2.FileRequest.SerializeToString,
            response_deserializer=RemoteFileSystem__pb2.FileResponse.FromString,
        )
        self.copy = channel.unary_unary(
            "/proto.RemoteFileSystemService/copy",
            request_serializer=RemoteFileSystem__pb2.FileRequest.SerializeToString,
            response_deserializer=RemoteFileSystem__pb2.FileResponse.FromString,
        )
        self.mkdir = channel.unary_unary(
            "/proto.RemoteFileSystemService/mkdir",
            request_serializer=RemoteFileSystem__pb2.FileRequest.SerializeToString,
            response_deserializer=RemoteFileSystem__pb2.FileResponse.FromString,
        )
        self.info = channel.unary_unary(
            "/proto.RemoteFileSystemService/info",
            request_serializer=RemoteFileSystem__pb2.FileRequest.SerializeToString,
            response_deserializer=RemoteFileSystem__pb2.FileResponse.FromString,
        )
        self.diskInfo = channel.unary_unary(
            "/proto.RemoteFileSystemService/diskInfo",
            request_serializer=RemoteFileSystem__pb2.DiskInfoRequest.SerializeToString,
            response_deserializer=RemoteFileSystem__pb2.DiskInfoResponse.FromString,
        )
        self.checkPathExist = channel.unary_unary(
            "/proto.RemoteFileSystemService/checkPathExist",
            request_serializer=RemoteFileSystem__pb2.CheckPathExistRequest.SerializeToString,
            response_deserializer=RemoteFileSystem__pb2.CheckPathResponse.FromString,
        )
        self.command = channel.unary_unary(
            "/proto.RemoteFileSystemService/command",
            request_serializer=RemoteFileSystem__pb2.systemCommandRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.generalResponse.FromString,
        )


class RemoteFileSystemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getRuntimeInfo(self, request, context):
        """! get runtime info"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def list(self, request, context):
        """! list path of files, folder"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def recursiveList(self, request, context):
        """! list path of files, folder"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def read(self, request, context):
        """! read content from remote file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def write(self, request, context):
        """! write content to remote file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def writeStream(self, request_iterator, context):
        """! write file stream"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def readStream(self, request, context):
        """! read file stream"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def rename(self, request, context):
        """! rename remote file or folder"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def remove(self, request, context):
        """! remove remote file or folder"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def copy(self, request, context):
        """! copy file: remote A -> remote B"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def mkdir(self, request, context):
        """! create remote directory"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def info(self, request, context):
        """! get remote file information"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def diskInfo(self, request, context):
        """! get remote disk info."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def checkPathExist(self, request, context):
        """! check remote file/folder exists"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def command(self, request, context):
        """system command"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RemoteFileSystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "getRuntimeInfo": grpc.unary_unary_rpc_method_handler(
            servicer.getRuntimeInfo,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RemoteFileSystem__pb2.RuntimeInfoResponse.SerializeToString,
        ),
        "list": grpc.unary_unary_rpc_method_handler(
            servicer.list,
            request_deserializer=RemoteFileSystem__pb2.FileRequest.FromString,
            response_serializer=RemoteFileSystem__pb2.FileResponse.SerializeToString,
        ),
        "recursiveList": grpc.unary_unary_rpc_method_handler(
            servicer.recursiveList,
            request_deserializer=RemoteFileSystem__pb2.FileRequest.FromString,
            response_serializer=RemoteFileSystem__pb2.FileResponse.SerializeToString,
        ),
        "read": grpc.unary_unary_rpc_method_handler(
            servicer.read,
            request_deserializer=RemoteFileSystem__pb2.FileRequest.FromString,
            response_serializer=RemoteFileSystem__pb2.FileResponse.SerializeToString,
        ),
        "write": grpc.unary_unary_rpc_method_handler(
            servicer.write,
            request_deserializer=RemoteFileSystem__pb2.FileInfo.FromString,
            response_serializer=RemoteFileSystem__pb2.FileResponse.SerializeToString,
        ),
        "writeStream": grpc.stream_unary_rpc_method_handler(
            servicer.writeStream,
            request_deserializer=RemoteFileSystem__pb2.FileStreamInfo.FromString,
            response_serializer=RemoteFileSystem__pb2.FileStreamResponse.SerializeToString,
        ),
        "readStream": grpc.unary_stream_rpc_method_handler(
            servicer.readStream,
            request_deserializer=RemoteFileSystem__pb2.FileRequest.FromString,
            response_serializer=RemoteFileSystem__pb2.FileStreamResponse.SerializeToString,
        ),
        "rename": grpc.unary_unary_rpc_method_handler(
            servicer.rename,
            request_deserializer=RemoteFileSystem__pb2.FileRequest.FromString,
            response_serializer=RemoteFileSystem__pb2.FileResponse.SerializeToString,
        ),
        "remove": grpc.unary_unary_rpc_method_handler(
            servicer.remove,
            request_deserializer=RemoteFileSystem__pb2.FileRequest.FromString,
            response_serializer=RemoteFileSystem__pb2.FileResponse.SerializeToString,
        ),
        "copy": grpc.unary_unary_rpc_method_handler(
            servicer.copy,
            request_deserializer=RemoteFileSystem__pb2.FileRequest.FromString,
            response_serializer=RemoteFileSystem__pb2.FileResponse.SerializeToString,
        ),
        "mkdir": grpc.unary_unary_rpc_method_handler(
            servicer.mkdir,
            request_deserializer=RemoteFileSystem__pb2.FileRequest.FromString,
            response_serializer=RemoteFileSystem__pb2.FileResponse.SerializeToString,
        ),
        "info": grpc.unary_unary_rpc_method_handler(
            servicer.info,
            request_deserializer=RemoteFileSystem__pb2.FileRequest.FromString,
            response_serializer=RemoteFileSystem__pb2.FileResponse.SerializeToString,
        ),
        "diskInfo": grpc.unary_unary_rpc_method_handler(
            servicer.diskInfo,
            request_deserializer=RemoteFileSystem__pb2.DiskInfoRequest.FromString,
            response_serializer=RemoteFileSystem__pb2.DiskInfoResponse.SerializeToString,
        ),
        "checkPathExist": grpc.unary_unary_rpc_method_handler(
            servicer.checkPathExist,
            request_deserializer=RemoteFileSystem__pb2.CheckPathExistRequest.FromString,
            response_serializer=RemoteFileSystem__pb2.CheckPathResponse.SerializeToString,
        ),
        "command": grpc.unary_unary_rpc_method_handler(
            servicer.command,
            request_deserializer=RemoteFileSystem__pb2.systemCommandRequest.FromString,
            response_serializer=CommonDefs__pb2.generalResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "proto.RemoteFileSystemService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class RemoteFileSystemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getRuntimeInfo(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.RemoteFileSystemService/getRuntimeInfo",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RemoteFileSystem__pb2.RuntimeInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def list(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.RemoteFileSystemService/list",
            RemoteFileSystem__pb2.FileRequest.SerializeToString,
            RemoteFileSystem__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def recursiveList(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.RemoteFileSystemService/recursiveList",
            RemoteFileSystem__pb2.FileRequest.SerializeToString,
            RemoteFileSystem__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def read(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.RemoteFileSystemService/read",
            RemoteFileSystem__pb2.FileRequest.SerializeToString,
            RemoteFileSystem__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def write(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.RemoteFileSystemService/write",
            RemoteFileSystem__pb2.FileInfo.SerializeToString,
            RemoteFileSystem__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def writeStream(
            request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/proto.RemoteFileSystemService/writeStream",
            RemoteFileSystem__pb2.FileStreamInfo.SerializeToString,
            RemoteFileSystem__pb2.FileStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def readStream(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/proto.RemoteFileSystemService/readStream",
            RemoteFileSystem__pb2.FileRequest.SerializeToString,
            RemoteFileSystem__pb2.FileStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def rename(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.RemoteFileSystemService/rename",
            RemoteFileSystem__pb2.FileRequest.SerializeToString,
            RemoteFileSystem__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def remove(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.RemoteFileSystemService/remove",
            RemoteFileSystem__pb2.FileRequest.SerializeToString,
            RemoteFileSystem__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def copy(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.RemoteFileSystemService/copy",
            RemoteFileSystem__pb2.FileRequest.SerializeToString,
            RemoteFileSystem__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def mkdir(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.RemoteFileSystemService/mkdir",
            RemoteFileSystem__pb2.FileRequest.SerializeToString,
            RemoteFileSystem__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def info(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.RemoteFileSystemService/info",
            RemoteFileSystem__pb2.FileRequest.SerializeToString,
            RemoteFileSystem__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def diskInfo(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.RemoteFileSystemService/diskInfo",
            RemoteFileSystem__pb2.DiskInfoRequest.SerializeToString,
            RemoteFileSystem__pb2.DiskInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def checkPathExist(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.RemoteFileSystemService/checkPathExist",
            RemoteFileSystem__pb2.CheckPathExistRequest.SerializeToString,
            RemoteFileSystem__pb2.CheckPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def command(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.RemoteFileSystemService/command",
            RemoteFileSystem__pb2.systemCommandRequest.SerializeToString,
            CommonDefs__pb2.generalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
