# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

import pyrdk.protos.pb2.CommonDefs_pb2 as CommonDefs__pb2
import pyrdk.protos.pb2.RobotServiceExternalDeviceCfg_pb2 as RobotServiceExternalDeviceCfg__pb2


class ExternalDeviceCfgServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExternalAxisUserCfg = channel.unary_unary(
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/GetExternalAxisUserCfg",
            request_serializer=RobotServiceExternalDeviceCfg__pb2.GetExternalAxisUserCfgRequest.SerializeToString,
            response_deserializer=RobotServiceExternalDeviceCfg__pb2.GetExternalAxisUserCfgResponse.FromString,
        )
        self.GetMainArmExternalAxisUserCfg = channel.unary_unary(
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/GetMainArmExternalAxisUserCfg",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternalDeviceCfg__pb2.GetExternalAxisUserCfgResponse.FromString,
        )
        self.SetExternalAxisUserCfg = channel.unary_unary(
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/SetExternalAxisUserCfg",
            request_serializer=RobotServiceExternalDeviceCfg__pb2.SetExternalAxisUserCfgRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.FvrReturnValue.FromString,
        )
        self.EnableExternalAxisCfg = channel.unary_unary(
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/EnableExternalAxisCfg",
            request_serializer=RobotServiceExternalDeviceCfg__pb2.EnableExternalAxisCfgRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.FvrReturnValue.FromString,
        )
        self.GetEnableExternalAxisUserCfg = channel.unary_unary(
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/GetEnableExternalAxisUserCfg",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternalDeviceCfg__pb2.GetEnableExternalAxisUserCfgResponse.FromString,
        )
        self.GetArmDriverParamFilePath = channel.unary_unary(
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/GetArmDriverParamFilePath",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternalDeviceCfg__pb2.GetArmDriverParamFilePathResponse.FromString,
        )
        self.GetHardwareExternalAxisStatus = channel.unary_unary(
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/GetHardwareExternalAxisStatus",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternalDeviceCfg__pb2.GetHardwareExternalAxisStatusResponse.FromString,
        )
        self.GetFTSensorUserCfgStatus = channel.unary_unary(
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/GetFTSensorUserCfgStatus",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternalDeviceCfg__pb2.GetFTSensorUserCfgStatusResponse.FromString,
        )
        self.ImportWsbSlaveCfgFile = channel.unary_unary(
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/ImportWsbSlaveCfgFile",
            request_serializer=RobotServiceExternalDeviceCfg__pb2.ImportWsbSlaveCfgFileRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.FvrReturnValue.FromString,
        )
        self.EnableFTSensorUserCfg = channel.unary_unary(
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/EnableFTSensorUserCfg",
            request_serializer=RobotServiceExternalDeviceCfg__pb2.EnableFTSensorUserCfgRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.FvrReturnValue.FromString,
        )
        self.SetMotionBarSerialPortCfg = channel.unary_unary(
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/SetMotionBarSerialPortCfg",
            request_serializer=RobotServiceExternalDeviceCfg__pb2.SetMotionBarSerialPortCfgRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.FvrReturnValue.FromString,
        )
        self.GetMotionBarSerialPortCfg = channel.unary_unary(
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/GetMotionBarSerialPortCfg",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternalDeviceCfg__pb2.MotionBarSerialPortState.FromString,
        )
        self.CheckMotionBarState = channel.unary_unary(
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/CheckMotionBarState",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternalDeviceCfg__pb2.MotionBarSerialPortState.FromString,
        )


class ExternalDeviceCfgServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetExternalAxisUserCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMainArmExternalAxisUserCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetExternalAxisUserCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EnableExternalAxisCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetEnableExternalAxisUserCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetArmDriverParamFilePath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetHardwareExternalAxisStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFTSensorUserCfgStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ImportWsbSlaveCfgFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EnableFTSensorUserCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetMotionBarSerialPortCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMotionBarSerialPortCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CheckMotionBarState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ExternalDeviceCfgServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetExternalAxisUserCfg": grpc.unary_unary_rpc_method_handler(
            servicer.GetExternalAxisUserCfg,
            request_deserializer=RobotServiceExternalDeviceCfg__pb2.GetExternalAxisUserCfgRequest.FromString,
            response_serializer=RobotServiceExternalDeviceCfg__pb2.GetExternalAxisUserCfgResponse.SerializeToString,
        ),
        "GetMainArmExternalAxisUserCfg": grpc.unary_unary_rpc_method_handler(
            servicer.GetMainArmExternalAxisUserCfg,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternalDeviceCfg__pb2.GetExternalAxisUserCfgResponse.SerializeToString,
        ),
        "SetExternalAxisUserCfg": grpc.unary_unary_rpc_method_handler(
            servicer.SetExternalAxisUserCfg,
            request_deserializer=RobotServiceExternalDeviceCfg__pb2.SetExternalAxisUserCfgRequest.FromString,
            response_serializer=CommonDefs__pb2.FvrReturnValue.SerializeToString,
        ),
        "EnableExternalAxisCfg": grpc.unary_unary_rpc_method_handler(
            servicer.EnableExternalAxisCfg,
            request_deserializer=RobotServiceExternalDeviceCfg__pb2.EnableExternalAxisCfgRequest.FromString,
            response_serializer=CommonDefs__pb2.FvrReturnValue.SerializeToString,
        ),
        "GetEnableExternalAxisUserCfg": grpc.unary_unary_rpc_method_handler(
            servicer.GetEnableExternalAxisUserCfg,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternalDeviceCfg__pb2.GetEnableExternalAxisUserCfgResponse.SerializeToString,
        ),
        "GetArmDriverParamFilePath": grpc.unary_unary_rpc_method_handler(
            servicer.GetArmDriverParamFilePath,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternalDeviceCfg__pb2.GetArmDriverParamFilePathResponse.SerializeToString,
        ),
        "GetHardwareExternalAxisStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetHardwareExternalAxisStatus,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternalDeviceCfg__pb2.GetHardwareExternalAxisStatusResponse.SerializeToString,
        ),
        "GetFTSensorUserCfgStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetFTSensorUserCfgStatus,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternalDeviceCfg__pb2.GetFTSensorUserCfgStatusResponse.SerializeToString,
        ),
        "ImportWsbSlaveCfgFile": grpc.unary_unary_rpc_method_handler(
            servicer.ImportWsbSlaveCfgFile,
            request_deserializer=RobotServiceExternalDeviceCfg__pb2.ImportWsbSlaveCfgFileRequest.FromString,
            response_serializer=CommonDefs__pb2.FvrReturnValue.SerializeToString,
        ),
        "EnableFTSensorUserCfg": grpc.unary_unary_rpc_method_handler(
            servicer.EnableFTSensorUserCfg,
            request_deserializer=RobotServiceExternalDeviceCfg__pb2.EnableFTSensorUserCfgRequest.FromString,
            response_serializer=CommonDefs__pb2.FvrReturnValue.SerializeToString,
        ),
        "SetMotionBarSerialPortCfg": grpc.unary_unary_rpc_method_handler(
            servicer.SetMotionBarSerialPortCfg,
            request_deserializer=RobotServiceExternalDeviceCfg__pb2.SetMotionBarSerialPortCfgRequest.FromString,
            response_serializer=CommonDefs__pb2.FvrReturnValue.SerializeToString,
        ),
        "GetMotionBarSerialPortCfg": grpc.unary_unary_rpc_method_handler(
            servicer.GetMotionBarSerialPortCfg,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternalDeviceCfg__pb2.MotionBarSerialPortState.SerializeToString,
        ),
        "CheckMotionBarState": grpc.unary_unary_rpc_method_handler(
            servicer.CheckMotionBarState,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternalDeviceCfg__pb2.MotionBarSerialPortState.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "proto.robot.externalDeviceCfg.ExternalDeviceCfgService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ExternalDeviceCfgService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetExternalAxisUserCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/GetExternalAxisUserCfg",
            RobotServiceExternalDeviceCfg__pb2.GetExternalAxisUserCfgRequest.SerializeToString,
            RobotServiceExternalDeviceCfg__pb2.GetExternalAxisUserCfgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetMainArmExternalAxisUserCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/GetMainArmExternalAxisUserCfg",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternalDeviceCfg__pb2.GetExternalAxisUserCfgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SetExternalAxisUserCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/SetExternalAxisUserCfg",
            RobotServiceExternalDeviceCfg__pb2.SetExternalAxisUserCfgRequest.SerializeToString,
            CommonDefs__pb2.FvrReturnValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def EnableExternalAxisCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/EnableExternalAxisCfg",
            RobotServiceExternalDeviceCfg__pb2.EnableExternalAxisCfgRequest.SerializeToString,
            CommonDefs__pb2.FvrReturnValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetEnableExternalAxisUserCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/GetEnableExternalAxisUserCfg",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternalDeviceCfg__pb2.GetEnableExternalAxisUserCfgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetArmDriverParamFilePath(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/GetArmDriverParamFilePath",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternalDeviceCfg__pb2.GetArmDriverParamFilePathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetHardwareExternalAxisStatus(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/GetHardwareExternalAxisStatus",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternalDeviceCfg__pb2.GetHardwareExternalAxisStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetFTSensorUserCfgStatus(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/GetFTSensorUserCfgStatus",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternalDeviceCfg__pb2.GetFTSensorUserCfgStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ImportWsbSlaveCfgFile(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/ImportWsbSlaveCfgFile",
            RobotServiceExternalDeviceCfg__pb2.ImportWsbSlaveCfgFileRequest.SerializeToString,
            CommonDefs__pb2.FvrReturnValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def EnableFTSensorUserCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/EnableFTSensorUserCfg",
            RobotServiceExternalDeviceCfg__pb2.EnableFTSensorUserCfgRequest.SerializeToString,
            CommonDefs__pb2.FvrReturnValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SetMotionBarSerialPortCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/SetMotionBarSerialPortCfg",
            RobotServiceExternalDeviceCfg__pb2.SetMotionBarSerialPortCfgRequest.SerializeToString,
            CommonDefs__pb2.FvrReturnValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetMotionBarSerialPortCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/GetMotionBarSerialPortCfg",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternalDeviceCfg__pb2.MotionBarSerialPortState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CheckMotionBarState(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalDeviceCfg.ExternalDeviceCfgService/CheckMotionBarState",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternalDeviceCfg__pb2.MotionBarSerialPortState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
