# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

import pyrdk.protos.pb2.CommonDefs_pb2 as CommonDefs__pb2
import pyrdk.protos.pb2.RobotServiceSystem_pb2 as RobotServiceSystem__pb2


class SystemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateGlobalVar = channel.unary_unary(
            "/proto.robot.system.SystemService/UpdateGlobalVar",
            request_serializer=RobotServiceSystem__pb2.UpdateGlobalVarRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.FvrReturnValue.FromString,
        )
        self.UpdateUserDefinedJntParams = channel.unary_unary(
            "/proto.robot.system.SystemService/UpdateUserDefinedJntParams",
            request_serializer=RobotServiceSystem__pb2.UpdateUserDefinedJntParamsRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.FvrReturnValue.FromString,
        )
        self.GetUpdatedSysConfig = channel.unary_unary(
            "/proto.robot.system.SystemService/GetUpdatedSysConfig",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceSystem__pb2.GetUpdatedSysConfigResponse.FromString,
        )
        self.SaveUpdatedSysConfig = channel.unary_unary(
            "/proto.robot.system.SystemService/SaveUpdatedSysConfig",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=CommonDefs__pb2.FvrReturnValue.FromString,
        )
        self.SetServoState = channel.unary_unary(
            "/proto.robot.system.SystemService/SetServoState",
            request_serializer=RobotServiceSystem__pb2.SetServoStateRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.FvrReturnValue.FromString,
        )
        self.ExecuteSystemCmd = channel.unary_unary(
            "/proto.robot.system.SystemService/ExecuteSystemCmd",
            request_serializer=RobotServiceSystem__pb2.ExecuteSystemCmdRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.FvrReturnValue.FromString,
        )
        self.PreviewRobotState = channel.unary_unary(
            "/proto.robot.system.SystemService/PreviewRobotState",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceSystem__pb2.PreviewRobotStateResponse.FromString,
        )


class SystemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateGlobalVar(self, request, context):
        """! update global var"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateUserDefinedJntParams(self, request, context):
        """! send user defined joint position params by uiState"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUpdatedSysConfig(self, request, context):
        """! get updated system config"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SaveUpdatedSysConfig(self, request, context):
        """! save updated system config to file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetServoState(self, request, context):
        """! set servo state"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExecuteSystemCmd(self, request, context):
        """! execute system command"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PreviewRobotState(self, request, context):
        """! preview robotState"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "UpdateGlobalVar": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateGlobalVar,
            request_deserializer=RobotServiceSystem__pb2.UpdateGlobalVarRequest.FromString,
            response_serializer=CommonDefs__pb2.FvrReturnValue.SerializeToString,
        ),
        "UpdateUserDefinedJntParams": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateUserDefinedJntParams,
            request_deserializer=RobotServiceSystem__pb2.UpdateUserDefinedJntParamsRequest.FromString,
            response_serializer=CommonDefs__pb2.FvrReturnValue.SerializeToString,
        ),
        "GetUpdatedSysConfig": grpc.unary_unary_rpc_method_handler(
            servicer.GetUpdatedSysConfig,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceSystem__pb2.GetUpdatedSysConfigResponse.SerializeToString,
        ),
        "SaveUpdatedSysConfig": grpc.unary_unary_rpc_method_handler(
            servicer.SaveUpdatedSysConfig,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=CommonDefs__pb2.FvrReturnValue.SerializeToString,
        ),
        "SetServoState": grpc.unary_unary_rpc_method_handler(
            servicer.SetServoState,
            request_deserializer=RobotServiceSystem__pb2.SetServoStateRequest.FromString,
            response_serializer=CommonDefs__pb2.FvrReturnValue.SerializeToString,
        ),
        "ExecuteSystemCmd": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteSystemCmd,
            request_deserializer=RobotServiceSystem__pb2.ExecuteSystemCmdRequest.FromString,
            response_serializer=CommonDefs__pb2.FvrReturnValue.SerializeToString,
        ),
        "PreviewRobotState": grpc.unary_unary_rpc_method_handler(
            servicer.PreviewRobotState,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceSystem__pb2.PreviewRobotStateResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "proto.robot.system.SystemService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class SystemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateGlobalVar(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.system.SystemService/UpdateGlobalVar",
            RobotServiceSystem__pb2.UpdateGlobalVarRequest.SerializeToString,
            CommonDefs__pb2.FvrReturnValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UpdateUserDefinedJntParams(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.system.SystemService/UpdateUserDefinedJntParams",
            RobotServiceSystem__pb2.UpdateUserDefinedJntParamsRequest.SerializeToString,
            CommonDefs__pb2.FvrReturnValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetUpdatedSysConfig(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.system.SystemService/GetUpdatedSysConfig",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceSystem__pb2.GetUpdatedSysConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SaveUpdatedSysConfig(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.system.SystemService/SaveUpdatedSysConfig",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            CommonDefs__pb2.FvrReturnValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SetServoState(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.system.SystemService/SetServoState",
            RobotServiceSystem__pb2.SetServoStateRequest.SerializeToString,
            CommonDefs__pb2.FvrReturnValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ExecuteSystemCmd(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.system.SystemService/ExecuteSystemCmd",
            RobotServiceSystem__pb2.ExecuteSystemCmdRequest.SerializeToString,
            CommonDefs__pb2.FvrReturnValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PreviewRobotState(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.system.SystemService/PreviewRobotState",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceSystem__pb2.PreviewRobotStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
