# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

import pyrdk.protos.pb2.CommonDefs_pb2 as CommonDefs__pb2
import pyrdk.protos.pb2.RobotServiceExternal_pb2 as RobotServiceExternal__pb2


class RobotServiceExternalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getCurrentExternalModeCfg = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/getCurrentExternalModeCfg",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternal__pb2.queryExternalModeCfgResponse.FromString,
        )
        self.getExternalModeCfg = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/getExternalModeCfg",
            request_serializer=RobotServiceExternal__pb2.queryExternalModeCfgRequest.SerializeToString,
            response_deserializer=RobotServiceExternal__pb2.queryExternalModeCfgResponse.FromString,
        )
        self.setExternalModeCfg = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/setExternalModeCfg",
            request_serializer=RobotServiceExternal__pb2.externalModeCfg.SerializeToString,
            response_deserializer=CommonDefs__pb2.generalResponse.FromString,
        )
        self.getExternalGPIOCfg = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/getExternalGPIOCfg",
            request_serializer=RobotServiceExternal__pb2.externalGPIOCfgRequest.SerializeToString,
            response_deserializer=RobotServiceExternal__pb2.queryExternalGPIOCfgResponse.FromString,
        )
        self.setExternalGPIOEnable = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/setExternalGPIOEnable",
            request_serializer=RobotServiceExternal__pb2.setExternalGPIOEnableRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.generalResponse.FromString,
        )
        self.setExternalPlanIndex = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/setExternalPlanIndex",
            request_serializer=RobotServiceExternal__pb2.SetExternalPlanIndexRequest.SerializeToString,
            response_deserializer=RobotServiceExternal__pb2.SetExternalPlanIndexResponse.FromString,
        )
        self.getCurrentRunningPlanParams = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/getCurrentRunningPlanParams",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternal__pb2.GetCurrentRunningPlanResponse.FromString,
        )
        self.getExternalPlanIndexList = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/getExternalPlanIndexList",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternal__pb2.ExternalPlanIndexDataList.FromString,
        )
        self.getUIAssignedPlanNameList = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/getUIAssignedPlanNameList",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternal__pb2.PlanNameList.FromString,
        )
        self.setupIOPortSimPanel = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/setupIOPortSimPanel",
            request_serializer=RobotServiceExternal__pb2.configIOPortSimPanelRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.generalResponse.FromString,
        )
        self.simulatorIOStatePort = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/simulatorIOStatePort",
            request_serializer=RobotServiceExternal__pb2.simIOStatePortRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.generalResponse.FromString,
        )
        self.getIOPortSimPanel = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/getIOPortSimPanel",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternal__pb2.loadIOPortSimPanelResponse.FromString,
        )
        self.sendCommandPortData = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/sendCommandPortData",
            request_serializer=RobotServiceExternal__pb2.commandPortRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.generalResponse.FromString,
        )
        self.setIOPortSimMode = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/setIOPortSimMode",
            request_serializer=RobotServiceExternal__pb2.setIOSimModeRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.generalResponse.FromString,
        )
        self.getIOSimMode = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExternal/getIOSimMode",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternal__pb2.getIOSimModeResponse.FromString,
        )


class RobotServiceExternalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getCurrentExternalModeCfg(self, request, context):
        """! get current external mode configure"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def getExternalModeCfg(self, request, context):
        """! get external mode cfg"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def setExternalModeCfg(self, request, context):
        """! set external mode cfg"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def getExternalGPIOCfg(self, request, context):
        """! get external GPIO params"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def setExternalGPIOEnable(self, request, context):
        """! set external GPIO enable flag"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def setExternalPlanIndex(self, request, context):
        """! save the plan index in external mode"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def getCurrentRunningPlanParams(self, request, context):
        """! get current running plan parameters,"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def getExternalPlanIndexList(self, request, context):
        """! get plan index in external mode list on run time"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def getUIAssignedPlanNameList(self, request, context):
        """! get plan name list in external mode on run time
        ! Note: this function should be renamed to getExternalPlanNameList
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def setupIOPortSimPanel(self, request, context):
        """! subscriber IO state ports"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def simulatorIOStatePort(self, request, context):
        """! simulator IO state port"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def getIOPortSimPanel(self, request, context):
        """! load remote IO state and command ports"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def sendCommandPortData(self, request, context):
        """! send I/O Port command"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def setIOPortSimMode(self, request, context):
        """! set remote IO Simulator mode"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def getIOSimMode(self, request, context):
        """! get IO simulator mode"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RobotServiceExternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "getCurrentExternalModeCfg": grpc.unary_unary_rpc_method_handler(
            servicer.getCurrentExternalModeCfg,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternal__pb2.queryExternalModeCfgResponse.SerializeToString,
        ),
        "getExternalModeCfg": grpc.unary_unary_rpc_method_handler(
            servicer.getExternalModeCfg,
            request_deserializer=RobotServiceExternal__pb2.queryExternalModeCfgRequest.FromString,
            response_serializer=RobotServiceExternal__pb2.queryExternalModeCfgResponse.SerializeToString,
        ),
        "setExternalModeCfg": grpc.unary_unary_rpc_method_handler(
            servicer.setExternalModeCfg,
            request_deserializer=RobotServiceExternal__pb2.externalModeCfg.FromString,
            response_serializer=CommonDefs__pb2.generalResponse.SerializeToString,
        ),
        "getExternalGPIOCfg": grpc.unary_unary_rpc_method_handler(
            servicer.getExternalGPIOCfg,
            request_deserializer=RobotServiceExternal__pb2.externalGPIOCfgRequest.FromString,
            response_serializer=RobotServiceExternal__pb2.queryExternalGPIOCfgResponse.SerializeToString,
        ),
        "setExternalGPIOEnable": grpc.unary_unary_rpc_method_handler(
            servicer.setExternalGPIOEnable,
            request_deserializer=RobotServiceExternal__pb2.setExternalGPIOEnableRequest.FromString,
            response_serializer=CommonDefs__pb2.generalResponse.SerializeToString,
        ),
        "setExternalPlanIndex": grpc.unary_unary_rpc_method_handler(
            servicer.setExternalPlanIndex,
            request_deserializer=RobotServiceExternal__pb2.SetExternalPlanIndexRequest.FromString,
            response_serializer=RobotServiceExternal__pb2.SetExternalPlanIndexResponse.SerializeToString,
        ),
        "getCurrentRunningPlanParams": grpc.unary_unary_rpc_method_handler(
            servicer.getCurrentRunningPlanParams,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternal__pb2.GetCurrentRunningPlanResponse.SerializeToString,
        ),
        "getExternalPlanIndexList": grpc.unary_unary_rpc_method_handler(
            servicer.getExternalPlanIndexList,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternal__pb2.ExternalPlanIndexDataList.SerializeToString,
        ),
        "getUIAssignedPlanNameList": grpc.unary_unary_rpc_method_handler(
            servicer.getUIAssignedPlanNameList,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternal__pb2.PlanNameList.SerializeToString,
        ),
        "setupIOPortSimPanel": grpc.unary_unary_rpc_method_handler(
            servicer.setupIOPortSimPanel,
            request_deserializer=RobotServiceExternal__pb2.configIOPortSimPanelRequest.FromString,
            response_serializer=CommonDefs__pb2.generalResponse.SerializeToString,
        ),
        "simulatorIOStatePort": grpc.unary_unary_rpc_method_handler(
            servicer.simulatorIOStatePort,
            request_deserializer=RobotServiceExternal__pb2.simIOStatePortRequest.FromString,
            response_serializer=CommonDefs__pb2.generalResponse.SerializeToString,
        ),
        "getIOPortSimPanel": grpc.unary_unary_rpc_method_handler(
            servicer.getIOPortSimPanel,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternal__pb2.loadIOPortSimPanelResponse.SerializeToString,
        ),
        "sendCommandPortData": grpc.unary_unary_rpc_method_handler(
            servicer.sendCommandPortData,
            request_deserializer=RobotServiceExternal__pb2.commandPortRequest.FromString,
            response_serializer=CommonDefs__pb2.generalResponse.SerializeToString,
        ),
        "setIOPortSimMode": grpc.unary_unary_rpc_method_handler(
            servicer.setIOPortSimMode,
            request_deserializer=RobotServiceExternal__pb2.setIOSimModeRequest.FromString,
            response_serializer=CommonDefs__pb2.generalResponse.SerializeToString,
        ),
        "getIOSimMode": grpc.unary_unary_rpc_method_handler(
            servicer.getIOSimMode,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternal__pb2.getIOSimModeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "proto_robotcmd_fromui.RobotServiceExternal", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class RobotServiceExternal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getCurrentExternalModeCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/getCurrentExternalModeCfg",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternal__pb2.queryExternalModeCfgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def getExternalModeCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/getExternalModeCfg",
            RobotServiceExternal__pb2.queryExternalModeCfgRequest.SerializeToString,
            RobotServiceExternal__pb2.queryExternalModeCfgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def setExternalModeCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/setExternalModeCfg",
            RobotServiceExternal__pb2.externalModeCfg.SerializeToString,
            CommonDefs__pb2.generalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def getExternalGPIOCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/getExternalGPIOCfg",
            RobotServiceExternal__pb2.externalGPIOCfgRequest.SerializeToString,
            RobotServiceExternal__pb2.queryExternalGPIOCfgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def setExternalGPIOEnable(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/setExternalGPIOEnable",
            RobotServiceExternal__pb2.setExternalGPIOEnableRequest.SerializeToString,
            CommonDefs__pb2.generalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def setExternalPlanIndex(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/setExternalPlanIndex",
            RobotServiceExternal__pb2.SetExternalPlanIndexRequest.SerializeToString,
            RobotServiceExternal__pb2.SetExternalPlanIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def getCurrentRunningPlanParams(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/getCurrentRunningPlanParams",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternal__pb2.GetCurrentRunningPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def getExternalPlanIndexList(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/getExternalPlanIndexList",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternal__pb2.ExternalPlanIndexDataList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def getUIAssignedPlanNameList(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/getUIAssignedPlanNameList",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternal__pb2.PlanNameList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def setupIOPortSimPanel(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/setupIOPortSimPanel",
            RobotServiceExternal__pb2.configIOPortSimPanelRequest.SerializeToString,
            CommonDefs__pb2.generalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def simulatorIOStatePort(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/simulatorIOStatePort",
            RobotServiceExternal__pb2.simIOStatePortRequest.SerializeToString,
            CommonDefs__pb2.generalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def getIOPortSimPanel(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/getIOPortSimPanel",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternal__pb2.loadIOPortSimPanelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def sendCommandPortData(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/sendCommandPortData",
            RobotServiceExternal__pb2.commandPortRequest.SerializeToString,
            CommonDefs__pb2.generalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def setIOPortSimMode(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/setIOPortSimMode",
            RobotServiceExternal__pb2.setIOSimModeRequest.SerializeToString,
            CommonDefs__pb2.generalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def getIOSimMode(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExternal/getIOSimMode",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternal__pb2.getIOSimModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )


class RobotServiceProjectStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getProjects = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceProject/getProjects",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternal__pb2.getPrjectInfoResponse.FromString,
        )


class RobotServiceProjectServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getProjects(self, request, context):
        """! get project info"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RobotServiceProjectServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "getProjects": grpc.unary_unary_rpc_method_handler(
            servicer.getProjects,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternal__pb2.getPrjectInfoResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "proto_robotcmd_fromui.RobotServiceProject", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class RobotServiceProject(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getProjects(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceProject/getProjects",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternal__pb2.getPrjectInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )


class RobotServiceExtenalAxisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getExternalAxisUserCfgData = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExtenalAxis/getExternalAxisUserCfgData",
            request_serializer=RobotServiceExternal__pb2.getExternalAxisUserCfgRequest.SerializeToString,
            response_deserializer=RobotServiceExternal__pb2.getExternalAxisUserCfgResponse.FromString,
        )
        self.setExternalAxisUserCfgData = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExtenalAxis/setExternalAxisUserCfgData",
            request_serializer=RobotServiceExternal__pb2.setExternalAxisUserCfgRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.generalResponse.FromString,
        )
        self.enableExternalAxisCfg = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExtenalAxis/enableExternalAxisCfg",
            request_serializer=RobotServiceExternal__pb2.enableExternalAxisCfgRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.generalResponse.FromString,
        )
        self.getEnableExternalAxisUserCfgData = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExtenalAxis/getEnableExternalAxisUserCfgData",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternal__pb2.getEnableExternalAxisUserCfgResponse.FromString,
        )
        self.getArmDriverParamFilePath = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExtenalAxis/getArmDriverParamFilePath",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternal__pb2.getArmDriverParamFilePathResponse.FromString,
        )
        self.getHardwareExternalAxisStatus = channel.unary_unary(
            "/proto_robotcmd_fromui.RobotServiceExtenalAxis/getHardwareExternalAxisStatus",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternal__pb2.getHardwareExternalAxisStatusResponse.FromString,
        )


class RobotServiceExtenalAxisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getExternalAxisUserCfgData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def setExternalAxisUserCfgData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def enableExternalAxisCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def getEnableExternalAxisUserCfgData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def getArmDriverParamFilePath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def getHardwareExternalAxisStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RobotServiceExtenalAxisServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "getExternalAxisUserCfgData": grpc.unary_unary_rpc_method_handler(
            servicer.getExternalAxisUserCfgData,
            request_deserializer=RobotServiceExternal__pb2.getExternalAxisUserCfgRequest.FromString,
            response_serializer=RobotServiceExternal__pb2.getExternalAxisUserCfgResponse.SerializeToString,
        ),
        "setExternalAxisUserCfgData": grpc.unary_unary_rpc_method_handler(
            servicer.setExternalAxisUserCfgData,
            request_deserializer=RobotServiceExternal__pb2.setExternalAxisUserCfgRequest.FromString,
            response_serializer=CommonDefs__pb2.generalResponse.SerializeToString,
        ),
        "enableExternalAxisCfg": grpc.unary_unary_rpc_method_handler(
            servicer.enableExternalAxisCfg,
            request_deserializer=RobotServiceExternal__pb2.enableExternalAxisCfgRequest.FromString,
            response_serializer=CommonDefs__pb2.generalResponse.SerializeToString,
        ),
        "getEnableExternalAxisUserCfgData": grpc.unary_unary_rpc_method_handler(
            servicer.getEnableExternalAxisUserCfgData,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternal__pb2.getEnableExternalAxisUserCfgResponse.SerializeToString,
        ),
        "getArmDriverParamFilePath": grpc.unary_unary_rpc_method_handler(
            servicer.getArmDriverParamFilePath,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternal__pb2.getArmDriverParamFilePathResponse.SerializeToString,
        ),
        "getHardwareExternalAxisStatus": grpc.unary_unary_rpc_method_handler(
            servicer.getHardwareExternalAxisStatus,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternal__pb2.getHardwareExternalAxisStatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "proto_robotcmd_fromui.RobotServiceExtenalAxis", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class RobotServiceExtenalAxis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getExternalAxisUserCfgData(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExtenalAxis/getExternalAxisUserCfgData",
            RobotServiceExternal__pb2.getExternalAxisUserCfgRequest.SerializeToString,
            RobotServiceExternal__pb2.getExternalAxisUserCfgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def setExternalAxisUserCfgData(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExtenalAxis/setExternalAxisUserCfgData",
            RobotServiceExternal__pb2.setExternalAxisUserCfgRequest.SerializeToString,
            CommonDefs__pb2.generalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def enableExternalAxisCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExtenalAxis/enableExternalAxisCfg",
            RobotServiceExternal__pb2.enableExternalAxisCfgRequest.SerializeToString,
            CommonDefs__pb2.generalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def getEnableExternalAxisUserCfgData(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExtenalAxis/getEnableExternalAxisUserCfgData",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternal__pb2.getEnableExternalAxisUserCfgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def getArmDriverParamFilePath(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExtenalAxis/getArmDriverParamFilePath",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternal__pb2.getArmDriverParamFilePathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def getHardwareExternalAxisStatus(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto_robotcmd_fromui.RobotServiceExtenalAxis/getHardwareExternalAxisStatus",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternal__pb2.getHardwareExternalAxisStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
