# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

import pyrdk.protos.pb2.CommonDefs_pb2 as CommonDefs__pb2
import pyrdk.protos.pb2.RobotServiceExternalAxis_pb2 as RobotServiceExternalAxis__pb2


class ExternalAxisServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExternalAxisUserCfg = channel.unary_unary(
            "/proto.robot.externalAxis.ExternalAxisService/GetExternalAxisUserCfg",
            request_serializer=RobotServiceExternalAxis__pb2.GetExternalAxisUserCfgRequest.SerializeToString,
            response_deserializer=RobotServiceExternalAxis__pb2.GetExternalAxisUserCfgResponse.FromString,
        )
        self.SetExternalAxisUserCfg = channel.unary_unary(
            "/proto.robot.externalAxis.ExternalAxisService/SetExternalAxisUserCfg",
            request_serializer=RobotServiceExternalAxis__pb2.SetExternalAxisUserCfgRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.FvrReturnValue.FromString,
        )
        self.EnableExternalAxisCfg = channel.unary_unary(
            "/proto.robot.externalAxis.ExternalAxisService/EnableExternalAxisCfg",
            request_serializer=RobotServiceExternalAxis__pb2.EnableExternalAxisCfgRequest.SerializeToString,
            response_deserializer=CommonDefs__pb2.FvrReturnValue.FromString,
        )
        self.GetEnableExternalAxisUserCfg = channel.unary_unary(
            "/proto.robot.externalAxis.ExternalAxisService/GetEnableExternalAxisUserCfg",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternalAxis__pb2.GetEnableExternalAxisUserCfgResponse.FromString,
        )
        self.GetArmDriverParamFilePath = channel.unary_unary(
            "/proto.robot.externalAxis.ExternalAxisService/GetArmDriverParamFilePath",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternalAxis__pb2.GetArmDriverParamFilePathResponse.FromString,
        )
        self.GetHardwareExternalAxisStatus = channel.unary_unary(
            "/proto.robot.externalAxis.ExternalAxisService/GetHardwareExternalAxisStatus",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceExternalAxis__pb2.GetHardwareExternalAxisStatusResponse.FromString,
        )


class ExternalAxisServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetExternalAxisUserCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetExternalAxisUserCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EnableExternalAxisCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetEnableExternalAxisUserCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetArmDriverParamFilePath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetHardwareExternalAxisStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ExternalAxisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetExternalAxisUserCfg": grpc.unary_unary_rpc_method_handler(
            servicer.GetExternalAxisUserCfg,
            request_deserializer=RobotServiceExternalAxis__pb2.GetExternalAxisUserCfgRequest.FromString,
            response_serializer=RobotServiceExternalAxis__pb2.GetExternalAxisUserCfgResponse.SerializeToString,
        ),
        "SetExternalAxisUserCfg": grpc.unary_unary_rpc_method_handler(
            servicer.SetExternalAxisUserCfg,
            request_deserializer=RobotServiceExternalAxis__pb2.SetExternalAxisUserCfgRequest.FromString,
            response_serializer=CommonDefs__pb2.FvrReturnValue.SerializeToString,
        ),
        "EnableExternalAxisCfg": grpc.unary_unary_rpc_method_handler(
            servicer.EnableExternalAxisCfg,
            request_deserializer=RobotServiceExternalAxis__pb2.EnableExternalAxisCfgRequest.FromString,
            response_serializer=CommonDefs__pb2.FvrReturnValue.SerializeToString,
        ),
        "GetEnableExternalAxisUserCfg": grpc.unary_unary_rpc_method_handler(
            servicer.GetEnableExternalAxisUserCfg,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternalAxis__pb2.GetEnableExternalAxisUserCfgResponse.SerializeToString,
        ),
        "GetArmDriverParamFilePath": grpc.unary_unary_rpc_method_handler(
            servicer.GetArmDriverParamFilePath,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternalAxis__pb2.GetArmDriverParamFilePathResponse.SerializeToString,
        ),
        "GetHardwareExternalAxisStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetHardwareExternalAxisStatus,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceExternalAxis__pb2.GetHardwareExternalAxisStatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "proto.robot.externalAxis.ExternalAxisService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ExternalAxisService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetExternalAxisUserCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalAxis.ExternalAxisService/GetExternalAxisUserCfg",
            RobotServiceExternalAxis__pb2.GetExternalAxisUserCfgRequest.SerializeToString,
            RobotServiceExternalAxis__pb2.GetExternalAxisUserCfgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SetExternalAxisUserCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalAxis.ExternalAxisService/SetExternalAxisUserCfg",
            RobotServiceExternalAxis__pb2.SetExternalAxisUserCfgRequest.SerializeToString,
            CommonDefs__pb2.FvrReturnValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def EnableExternalAxisCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalAxis.ExternalAxisService/EnableExternalAxisCfg",
            RobotServiceExternalAxis__pb2.EnableExternalAxisCfgRequest.SerializeToString,
            CommonDefs__pb2.FvrReturnValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetEnableExternalAxisUserCfg(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalAxis.ExternalAxisService/GetEnableExternalAxisUserCfg",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternalAxis__pb2.GetEnableExternalAxisUserCfgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetArmDriverParamFilePath(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalAxis.ExternalAxisService/GetArmDriverParamFilePath",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternalAxis__pb2.GetArmDriverParamFilePathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetHardwareExternalAxisStatus(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.externalAxis.ExternalAxisService/GetHardwareExternalAxisStatus",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceExternalAxis__pb2.GetHardwareExternalAxisStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
