# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

import pyrdk.protos.pb2.RobotServiceInfo_pb2 as RobotServiceInfo__pb2


class InfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDeviceInfo = channel.unary_unary(
            "/proto.robot.info.InfoService/GetDeviceInfo",
            request_serializer=RobotServiceInfo__pb2.GetDeviceInfoRequest.SerializeToString,
            response_deserializer=RobotServiceInfo__pb2.GetDeviceInfoResponse.FromString,
        )
        self.GetRobotRunAbsDir = channel.unary_unary(
            "/proto.robot.info.InfoService/GetRobotRunAbsDir",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceInfo__pb2.GetRobotRunAbsDirResponse.FromString,
        )
        self.GetRobotSysTime = channel.unary_unary(
            "/proto.robot.info.InfoService/GetRobotSysTime",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceInfo__pb2.GetRobotSysTimeResponse.FromString,
        )
        self.GetRobotVersionInfo = channel.unary_unary(
            "/proto.robot.info.InfoService/GetRobotVersionInfo",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceInfo__pb2.RobotVersionInfo.FromString,
        )
        self.GetRobotTimePeriod = channel.unary_unary(
            "/proto.robot.info.InfoService/GetRobotTimePeriod",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceInfo__pb2.GetRobotTimePeriodResponse.FromString,
        )
        self.GetDiskInfo = channel.unary_unary(
            "/proto.robot.info.InfoService/GetDiskInfo",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=RobotServiceInfo__pb2.GetDiskInfoResponse.FromString,
        )


class InfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDeviceInfo(self, request, context):
        """! get device information"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetRobotRunAbsDir(self, request, context):
        """! get robot absolute directory path"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetRobotSysTime(self, request, context):
        """! get robot system time"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetRobotVersionInfo(self, request, context):
        """! get robot version info"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetRobotTimePeriod(self, request, context):
        """! get robot system time period"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDiskInfo(self, request, context):
        """! get disk info"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_InfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetDeviceInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetDeviceInfo,
            request_deserializer=RobotServiceInfo__pb2.GetDeviceInfoRequest.FromString,
            response_serializer=RobotServiceInfo__pb2.GetDeviceInfoResponse.SerializeToString,
        ),
        "GetRobotRunAbsDir": grpc.unary_unary_rpc_method_handler(
            servicer.GetRobotRunAbsDir,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceInfo__pb2.GetRobotRunAbsDirResponse.SerializeToString,
        ),
        "GetRobotSysTime": grpc.unary_unary_rpc_method_handler(
            servicer.GetRobotSysTime,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceInfo__pb2.GetRobotSysTimeResponse.SerializeToString,
        ),
        "GetRobotVersionInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetRobotVersionInfo,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceInfo__pb2.RobotVersionInfo.SerializeToString,
        ),
        "GetRobotTimePeriod": grpc.unary_unary_rpc_method_handler(
            servicer.GetRobotTimePeriod,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceInfo__pb2.GetRobotTimePeriodResponse.SerializeToString,
        ),
        "GetDiskInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetDiskInfo,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=RobotServiceInfo__pb2.GetDiskInfoResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "proto.robot.info.InfoService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class InfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDeviceInfo(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.info.InfoService/GetDeviceInfo",
            RobotServiceInfo__pb2.GetDeviceInfoRequest.SerializeToString,
            RobotServiceInfo__pb2.GetDeviceInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetRobotRunAbsDir(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.info.InfoService/GetRobotRunAbsDir",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceInfo__pb2.GetRobotRunAbsDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetRobotSysTime(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.info.InfoService/GetRobotSysTime",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceInfo__pb2.GetRobotSysTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetRobotVersionInfo(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.info.InfoService/GetRobotVersionInfo",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceInfo__pb2.RobotVersionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetRobotTimePeriod(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.info.InfoService/GetRobotTimePeriod",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceInfo__pb2.GetRobotTimePeriodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetDiskInfo(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/proto.robot.info.InfoService/GetDiskInfo",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            RobotServiceInfo__pb2.GetDiskInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
